[package]
name = "performance-gpu-ensemble"
version = "0.1.0"
edition.workspace = true
publish = false

[features]
cuda-oxide = ["diffsol/cuda-oxide"]

[dependencies]
diffsol = { path = "../../crates/diffsol" }
num-traits = { workspace = true }
plotly = { workspace = true }
rayon = "1.10"
rand = "0.9"
rand_chacha = "0.9"
rand_distr = "0.5"
