extern "C" {
#include "mat_from_diagonal.cu"
#include "mat_get_diagonal.cu"
#include "mat_scale_add_assign.cu"
#include "mat_set_column.cu"
#include "mat_set_data_with_indices.cu"
#include "vec_add_assign_rhs.cu"
#include "vec_add_assign.cu"
#include "vec_add.cu"
#include "vec_assign_at_indices.cu"
#include "vec_copy_from_indices.cu"
#include "vec_copy.cu"
#include "vec_div_assign.cu"
#include "vec_fill.cu"
#include "vec_gather.cu"
#include "vec_mul_assign_scalar.cu"
#include "vec_mul_assign.cu"
#include "vec_mul_scalar.cu"
#include "vec_root_finding.cu"
#include "vec_scatter.cu"
#include "vec_squared_norm.cu"
#include "vec_sub_assign_rhs.cu"
#include "vec_sub_assign.cu"
#include "vec_sub.cu"
}