[package]
name = "external-linkage"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
diffsol = { path = "../../diffsol", features = ["diffsl-ext"] }
nalgebra = { workspace = true }
plotly = { workspace = true }