[book]
authors = ["martinjrobins"]
language = "en"
src = "src"
title = "Diffsol"

[preprocessor.tabs]

[output.html]
additional-css = ["theme/tabs.css"]
additional-js = ["theme/tabs.js"]
mathjax-support = true
