name: Continuous Benchmarking (PR)

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  benchmark_pr:
    name: Benchmark PR with Bencher
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and push Docker image
        run: |
          docker build -t registry.bencher.dev/diffsol:latest .
          docker login registry.bencher.dev -u diffsol --password-stdin <<< "${{ secrets.BENCHER_API_KEY }}"
          docker push registry.bencher.dev/diffsol:latest

      - uses: bencherdev/bencher@main

      - name: Track PR benchmarks
        run: |
          bencher run \
            --project diffsol \
            --key '${{ secrets.BENCHER_API_KEY }}' \
            --image diffsol:latest \
            --branch "$GITHUB_HEAD_REF" \
            --start-point "$GITHUB_BASE_REF" \
            --start-point-hash '${{ github.event.pull_request.base.sha }}' \
            --start-point-clone-thresholds \
            --start-point-reset \
            --testbed ubuntu-latest \
            --error-on-alert \
            --adapter rust_criterion \
            --github-actions '${{ secrets.GITHUB_TOKEN }}' \
            "cargo bench --bench ode_solvers_ci"
