name: Fork PR Benchmarks Run

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions: {}

jobs:
  benchmark_fork_pr:
    name: Run Fork PR Benchmarks
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: diffsol

      - name: Run benchmarks
        run: cargo bench --bench ode_solvers_ci > benchmark_results.txt 2>&1

      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark_results.txt
          path: ./benchmark_results.txt

      - name: Upload GitHub Pull Request Event
        uses: actions/upload-artifact@v4
        with:
          name: event.json
          path: ${{ github.event_path }}
